# Generated by Django 4.1.7 on 2023-04-21 01:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Z][a-z]{1,10}', message='Please introduce a valid name')], verbose_name='First Name')),
                ('lname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Z][a-z]{1,10}', message='Please introduce a valid name')], verbose_name='Last Name')),
                ('cnp', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('[1256][0-9]{2}[0-1][0-9][0-3][0-9]\\d{6}', message='Please introduce a CNP')], verbose_name='CNP')),
                ('email', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('[a-z]{2,10}\\.[a-z]{2,10}@stud\\.com', message='Please introduce a valid email')], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('07\\d{8}', message='Please introduce a valid phone number')], verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Z][a-z]{1,10}', message='Please introduce a valid name')], verbose_name='First Name')),
                ('lname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[A-Z][a-z]{1,10}', message='Please introduce a valid name')], verbose_name='Last Name')),
                ('rank', models.CharField(choices=[('P', 'Professor'), ('A', 'Associate'), ('L', 'Lecturer')], max_length=1, verbose_name='Rank')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2023)], verbose_name='Year')),
                ('teacher', models.ForeignKey(db_column='teacher', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='api.teacher', verbose_name='Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.FloatField(verbose_name='Session Grade')),
                ('retake', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Retake Grade')),
                ('course', models.ForeignKey(db_column='course', on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to='api.course', verbose_name='Course')),
                ('student', models.ForeignKey(db_column='student', on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='api.student', verbose_name='Student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
