# Generated by Django 4.1.7 on 2023-04-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_grade_session_alter_student_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='descr',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
