# Generated by Django 4.1.7 on 2023-05-07 18:18

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_course_department_alter_course_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')], verbose_name='First Name')),
                ('lname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')], verbose_name='Last Name')),
                ('bio', models.TextField(blank=True, default='', null=True, verbose_name='Bio')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, validators=[api.models.validate_choices], verbose_name='Gender')),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['cid']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['gid']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['sid']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['tid']},
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students', through='api.Grade', to='api.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='courses', through='api.Grade', to='api.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cnp',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('[1256][0-9]{2}[0-1][0-9][0-3][0-9]\\d{6}', message='Please introduce a valid CNP')], verbose_name='CNP'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='descr',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='api_course_name_5ceb92_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['course', 'student'], name='api_grade_course_6df970_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['session', 'retake'], name='api_grade_session_312100_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['fname', 'lname'], name='api_student_fname_5d206e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['fname', 'lname'], name='api_teacher_fname_986ca5_idx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
