# Generated by Django 4.1.7 on 2023-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_course_user_alter_grade_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cofirmation_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
