# Generated by Django 4.1.7 on 2023-05-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_cofirmation_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cofirmation_expiry_date',
            new_name='confirmation_expiry_date',
        ),
    ]
